### PR TITLE
(GH-570) Add GitHub Action scanning workflows

### LINKED ISSUE #570: Enable GitHub security and static analysis scanning
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

_No response_

### Describe The Solution. Why is it needed?

Add a GitHub Actions workflow that calls publicly available security and static analysis scanning tools to help check for any security or other issues.

### Additional Context

_No response_

### Related Issues

_No response_

### PR DESCRIPTION
**Pull request by flcdrg**
## Description Of Changes
Add GitHub Action workflows that run security and static analysis

- Add PSScriptAnalyzer workflow
- Add Codacy workflow
- Add DevSkim workflow
- Add CodeQL workflow

## Motivation and Context

Strengthen security checking and reduce risk of introducing vulnerabilities

## Testing
Tested in my repo

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [x] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v3 compatibility checked?

## Related Issue

Fixes #570

### CODE REVIEW

**Comment by mwallner** [comment]
This looks awesome! .. I just wonder if we should work on some of the [issues](https://github.com/chocolatey/boxstarter/security/code-scanning?query=pr%3A571+is%3Aopen) or we can/should add some exceptions for the hits.

**Comment by flcdrg** [comment]
Probably need to review them and figure out which ones are actionable and which ones may not be relevant.

**Review by mwallner — DISMISSED** [review]
LGTM, just one question on the cron schedule ... (I don'get get it :smile: )
=> so those workflows got two triggers, on push and also by schedule, - but wouldn't it be easier to grasp if we did use cron-expressions such as "@weekly" etc?

**Comment by flcdrg** [comment]
They were just the default values created by the GitHub templates, but yeah that sounds like a better idea

**Comment by flcdrg** [comment]
But unfortunately GitHub Actions don't support that - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

I will tweak the schedules though

**Review by mwallner — APPROVED** [review]

**Pull request merged**
