### PR TITLE
(GH-530) Enable/Disable News and Interest Icons

### LINKED ISSUE #530: Set-BoxstarterTaskbarOptions - Disable News and Interests Icon
### Checklist

- [X] I have verified this is the correct repository for opening this issue.
- [X] I have verified no other issues exist related to my request.

### Is Your Feature Request Related To A Problem? Please describe.

N/A: New Functionality.

### Describe The Solution. Why is it needed?

In a fresh Win10 install, the 'News and Interests' icon is shown by default, similar to the Bing search toolbox. Adding the functionality to disable it would be ideal.

Disabling it is straightforward, only a matter of setting `HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Feeds\ShellFeedsTaskbarViewMode`.

### Additional Context

N/A

### Related Issues

N/A

### PR DESCRIPTION
**Pull request by calmcl1**
## Description Of Changes
Adds a parameter `NewsIcons` to `Set-BoxstarterTaskbarOptions` to enable or disable the News and Interests icon that appears on new Win10 installs. The parameter mirrors the options made available when changing it from the taskbar context menu - 'Icon and Text' (`IconsText`), 'Icon Only' (`Icons`), or 'Hidden' (`Never`).

## Motivation and Context
This is another handy feature for taskbar customization.

## Testing
1. Tested on a clean sandbox install of W10 Pro.

### Operating Systems Testing
Win 10 Pro.

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [x] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [x] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issue

Fixes #530.

### CODE REVIEW

**Comment by flcdrg** [comment]
@gep13 is the logo commit supposed to be on this PR/branch?

**Comment by pauby** [comment]
@flcdrg The details are listed in [this commits' comments](https://github.com/chocolatey/boxstarter/pull/531/commits/a9549b91d71ddbd00d68775352409649bf9b225a).

**Comment by mwallner** [comment]
> @flcdrg The details are listed in [this commits' comments](https://github.com/chocolatey/boxstarter/pull/531/commits/a9549b91d71ddbd00d68775352409649bf9b225a).

Hi, it's been a while - is this still relevant? CC @gep13

**Review by mwallner — APPROVED** [review]
LGTM, thanks for your work!

**Pull request merged**
