### PR TITLE
(maint) Update install script URL

### PR DESCRIPTION
**Pull request by pauby**
## Description Of Changes
This is a minor change to update the URL used by the install script. We use `ch0.co` domain, so this is just a cosmetic change.

## Motivation and Context
Being consistent with our shortlinks.

## Testing
Clicked the link and it goes to the same URL as the old link.

### Operating Systems Testing
N/A

## Change Types Made

* [ ] Bug fix (non-breaking change).
* [ ] Feature / Enhancement (non-breaking change).
* [ ] Breaking change (fix or feature that could cause existing functionality to change).
* [ ] Documentation changes.
* [ ] PowerShell code changes.

## Change Checklist

* [ ] Requires a change to the documentation.
* [ ] Documentation has been updated.
* [ ] Tests to cover my changes, have been added.
* [ ] All new and existing tests passed?
* [ ] PowerShell code changes: PowerShell v2 compatibility checked?

## Related Issue
N/A

### CODE REVIEW

**Comment by pauby** [comment]
@mwallner I'm not sure if this URL is part of the work you are doing under #551?

**Review by gep13 — APPROVED** [review]
LGTM!

**Comment by gep13** [comment]
@pauby no objections from me for this to go in.  If you can update this branch on the head of develop, we can get this merged.

**Comment by pauby** [comment]
@gep13 that has been done now.

**Comment by mwallner** [comment]
> @mwallner I'm not sure if this URL is part of the work you are doing under #551?

not really, upgrading the _buildscript_ doesn't influence what's packed/bundled with Boxstarter at all, but this needed to be done anyway 🤗

**Pull request merged**
