### PR TITLE
(GH-394) chocolatey.dll no more

### LINKED ISSUE #247: Error running Boxstarter script with existing licensed Chocolatey
Installed latest Chocolatey 0.10.5, added my license for Professional and installed `chocolatey.extension` package.

Then ran boxstarter via `START http://boxstarter.org/package/url` and seeing these errors being displayed:

```
Error when registering components for 'chocolatey.licensed.infrastructure.app.registration.ContainerBinding':
 Exception has been thrown by the target of an invocation.
Error when setting configuration for 'chocolatey.licensed.infrastructure.app.builders.ConfigurationBuilder':
 Exception has been thrown by the target of an invocation.
Error when setting environment for 'chocolatey.licensed.infrastructure.app.configuration.EnvironmentSettings':
 Exception has been thrown by the target of an invocation.
```

### LINKED ISSUE #369: No Chocolatey installation
### What You Are Seeing?

The documentation of [Invoke-ChocolateyBoxstarter](https://github.com/chocolatey/boxstarter/blob/master/Boxstarter.Chocolatey/Invoke-ChocolateyBoxstarter.ps1) and [Install-BoxstarterPackage.ps1](https://github.com/chocolatey/boxstarter/blob/master/Boxstarter.Chocolatey/Install-BoxstarterPackage.ps1) state that Boxstarter will install Chocolatey on the machine if it does not exist. Using any of these functions on a fresh machine (using a local copy of Boxstarter) does not install `choco.exe`.

### What is Expected?

The above functions should either install Chocolatey, or the documentation should be updated.

### How Did You Get This To Happen? (Steps to Reproduce)

I am using [this repository](https://github.com/fwinkelbauer/windows-box-setup) to create a `box.zip` file which contains a copy of Boxstarter. Running `install-mybox.ps1` (included in `box.zip`) will install several Chocolatey packages on the machine (`C:\ProgramData\chocolatey\lib`), but there seems to be no `C:\ProgramData\chocolatey\bin\choco.exe`.

### LINKED ISSUE #394: Unbundling Chocolatey from Boxstarter and Installing Chocolatey Separately
To be able to use the neweset functionality within Chocolatey would require unbundling Chocolatey within Boxstarter and using the latest version from Chocolatey.org.

There looks to be quite a few iussues around this and @mwrock has mentioned some of them at #89. There is no further information around what has been patched so would be good to understand this.

Currently Boxstarter uses it's own version for remote installs but the remote installs could install, or use the current version of the Chocolatey package on the local machine to install remotely.

Bundling a version of Chocolatey helps to keep that version as a known entity - we know it works with Boxstarter so there will be no surprises. However we could install that particular version of Chocolatey and get the same outcome.

I've opened this to get a wider discussion on the merits of doing and not doing this.

Related #225, #247, #369

### LINKED ISSUE #423: Install-BoxstarterPackage and boxtarter.bat not behaving the same
### What You Are Seeing?
The result of running a boxstarter script with `Install-BoxstarterPackage` and `boxstarter.bat` to be inconsistent. A reboot is not triggered with `Install-BoxstarterPackage`, where `boxstarter.bat` does. 

### What Is Expected?
Both commands resulting in the same results.

### How Did You Get This To Happen? (Steps to Reproduce)
1. Create a boxstarter script with multiple reboots: (`DotNet4.7.2` and `veeam-explorer-for-microsoft-exchange-o365` require a reboot)
```
choco upgrade DotNet4.7.2
choco upgrade veeam-backup-for-microsoft-office-365 --params '"/server /powershell"'
choco upgrade veeam-backup-for-microsoft-office-365-console
choco upgrade veeam-explorer-for-microsoft-exchange-o365
choco upgrade veeam-explorer-for-microsoft-sharepoint-o365
choco upgrade veeam-backup-for-microsoft-office-365-management
```
2. Execute this script with `Install-BoxstarterPackage`

### Output Log
```sh
Packages requiring reboot:
 - veeam-explorer-for-microsoft-exchange-o365 (exit code 3010)
The recent package changes indicate a reboot is necessary.
 Please reboot at your earliest convenience.
Chocolatey reported an unsuccessful exit code of 3010. See C:\Users\vagrant\AppData\Local\Boxstarter\boxstarter.log for details.
+ Boxstarter finished Calling Chocolatey to install veeam-backup-for-microsoft-office-365-management. This may take several minutes to complete... 00:00:56.1124708
+ Boxstarter finished Calling Chocolatey to install veeam-backup-for-microsoft-office-365-management. This may take several minutes to complete... 00:00:56.1124708
Only an exit code of non-zero will fail the package by default. Set
 `--failonstderr` if you want error messages to also fail a script. See
 `choco -h` for details.
Environment Vars (like PATH) have changed. Close/reopen your shell to
 see the changes (or in powershell/cmd.exe just type `refreshenv`).
 The install of tmp335.tmp was successful.
  Software installed to 'C:\Program Files\Veeam\Backup and Replication\Explorers\SharePoint\'
Chocolatey installed 1/1 packages. 0 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Chocolatey : Chocolatey reported an unsuccessful exit code of 3010. See C:\Users\vagrant\AppData\Local\Boxstarter\boxstarter.log for details.
At C:\ProgramData\Boxstarter\Boxstarter.Chocolatey\Invoke-ChocolateyBoxstarter.ps1:199 char:5
+     Chocolatey install $bootstrapPackage -source $source -force:$forc ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,chocolatey
++ Boxstarter finished Calling Chocolatey to install tmp335.tmp. This may take several minutes to complete... 00:01:49.7503565
```

### LINKED ISSUE #442: $env:temp is changed on every run of Install-BoxstarterPackage
### What You Are Seeing?

`$env:temp` is changed on every run of `Install-BoxstarterPackage`

### How Did You Get This To Happen? (Steps to Reproduce)

I am running `Boxstarter v2.12.0` and `Chocolatey v0.10.15` under Windows 10

Here is my script to reproduce it.  The same behaviour can be observed in `Boxstarter Shell` or `Powershell`

```
# uncomment following line if running in Powershell
# Import-Module Boxstarter.Chocolatey
$filename = "$env:userprofile\test_script.ps1"
Set-Content -Path $filename -Value 'Write-Host "env:temp=$env:temp"'
Install-BoxstarterPackage -PackageName "$filename"
```
every time you call `Install-BoxstarterPackage -PackageName "$filename"`  additional subdirectories `chocolatey\chocolatey` are appended to `$env:temp` 
```
env:temp=C:\Users\map\AppData\Local\Temp\chocolatey\chocolatey
env:temp=C:\Users\map\AppData\Local\Temp\chocolatey\chocolatey\chocolatey\chocolatey
env:temp=C:\Users\map\AppData\Local\Temp\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey\chocolatey
```
#### Related Issues?
Maybe following issues are related to this one:
- https://github.com/chocolatey/boxstarter/issues/241
- https://github.com/chocolatey/boxstarter/issues/416

### LINKED ISSUE #455: Error when installing more than one choco font package
### What You Are Seeing?

Strange error when installing font choco packages via Boxtarter

### What Is Expected?

Both choco packages install successfully which is what happens when executing outside of Boxstarter

### How Did You Get This To Happen? (Steps to Reproduce)

Create a Boxstarter package with the following

> cinst cascadia-code-nerd-font
cinst sourcecodepro

### Output Log

edit: removed public gist of logs - key log output

> ERROR: Cannot add type. The type name 'FontResource.AddRemoveFonts' already exists.
The install of cascadia-code-nerd-font was NOT successful.

### PR DESCRIPTION
**Pull request by mwallner**
## Description
+ rip out chocolatey.dll (use choco.exe from $env:ChocolateyInstall)
+ install chocolatey from nupkg if not present (local + remote)

## Related Issue

Fixes #247
Fixes #369
Fixes #394
Fixes #423
Fixes #442
Fixes #455

## Motivation and Context
To be able to use the neweset functionality within Chocolatey would require unbundling Chocolatey within Boxstarter and using the latest* version from Chocolatey.org.

With this PR, Boxstarter will always try to use the Chocolatey version from $env:ChocolateyInstall or install Chocolatey from a chocolatey.nupkg that comes with Boxstarter and should easily be updated whenever a new version of Chocolatey is released. (I intentionally do not use 'latest' here, because there might be unforseen issues with a newer version - hence it's safer to stick with a 'known-to-be-good' version until verified/tested. / as of today, Boxstarter would 'ship' with Chocolatey 0.11.3)

Currently Boxstarter uses it's own version for remote installs but the remote installs could install, or use the current version of the Chocolatey package on the local machine to install remotely.

## How Has This Been Tested?
Mainly on my dev-pc, use `psake Package` in the "buildscripts" directory to build artifacts that can be installed via chocolatey or simply use `boxstartershell.ps1` (note: you still need to `psake Package` before!) and use `Install-BoxstarterPackage` on a remote host.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/chocolatey/boxstarter/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by flcdrg — APPROVED** [review]

**Comment by Baune8D** [comment]
Adding feedback to this PR instead as requested by @pauby 

## Installation of remote package does not start with 2.13.16 artifacts

### What You Are Seeing?

Boxstarter never initiates remote install and just hangs on `Boxstarter starting Calling Chocolatey to install MagicScript. This may take several minutes to complete...`

image

I can verify that remoting works, because i can see Boxstarter trigging scripts on the remote machine on setup and teardown.

### What Is Expected?

Remote install is expected to start.

### How Did You Get This To Happen? (Steps to Reproduce)

This issue only happens with the 2.13.16 artifacts from AppVeyor https://ci.appveyor.com/project/chocolatey/boxstarter/builds/41341291/artifacts

Using Boxstarter 2.13.0 the remote installations starts correctly.

Remote install is kicked off from the host with `Install-BoxstarterPackage -ComputerName $hostname -PackageName $package -Credential $cred -StopOnPackageFailure` against a Hyper-V VM (Generation 2, Configuration 10).

Host is using Chocolatey 0.11.3

## Installation of chocolatey package triggers verbose information and ends in a loop using 2.13.16 artifacts

### What You Are Seeing?

When installing chocolatey package through Boxstarter 2.13.16, it triggers alot of verbose information and ulimately ends in a loop with the message `Checking for other running MSIEXEC installers...`

### What Is Expected?

Chocolatey package should install correctly and without verbose information.

### How Did You Get This To Happen? (Steps to Reproduce)

Calling `choco install 'git' --no-progress` in a Boxstarter package.

This issue only happens with the 2.13.16 artifacts from AppVeyor https://ci.appveyor.com/project/chocolatey/boxstarter/builds/41341291/artifacts

Using Boxstarter 2.13.0 the installation runs correctly.

### Output Log

Log from `%LOCALAPPDATA%\Boxstarter\boxstarter.log`
https://gist.github.com/Baune8D/f5618641b173d5c150dc33e94ba77526

**Comment by mwallner** [comment]
> Boxstarter never initiates remote install and just hangs on `Boxstarter starting Calling Chocolatey to install MagicScript. This may take several minutes to complete...`
> ... 
> Remote install is expected to start.

Hey @Baune8D , thanks again for your effort!
I managed to figure out what's going wrong here and will soon be able to provide a fix, stay tuned!

(note/memo: `$env:temp` changes when Boxstarter invokes choco.exe (+via scheduled task),- choco.exe appends `/chocolatey`which leads to `BoxstarterTask.ps1 / .stream` files not being at the expected location,-  nothing happens)

**Comment by mwallner** [comment]
hey @Baune8D , @flcdrg - could I ask you to take the latest Travis CI binaries for a spin? - I really want to get this out asap but also try not to break any use case I haven't got on my radar.

**Comment by mwallner** [comment]
I have yet to do some testing and update the docs, I'm not entirely sure if opening a new process for invoking chocolatey `Start-Process choco.exe` and loading Boxstarter context by "injecting a extension to sideload Boxstarter" will break any currently possible scenario.

so far I've tested:
* basic `Install-BoxstarterPackage` (local + remote) - using packages from the community repo
* basic `Install-BoxstarterPackage` (local + remote) - using custom packages (`New-BoxstarterPackage` + `Invoke-BoxstarterBuild`) that contain Boxstarter commands (`Invoke-Reboot`) 
* Chocolatey 0.11.3 will be installed by using this version of Boxstarter if no other version is present before (looking at `$env:ChocolateyInstall`)
* Chocolatey Business extension is able to load without error - using C4B commands from Boxstarter packages _should_ be possible

**Comment by flcdrg** [comment]
I'll try to give it a spin.

I think this should definitely be a major version release, so that would also be a hint that there's a chance of behaviour changing.

**Comment by Baune8D** [comment]
@mwallner Excited to give this another run! 😄 

I'm currently running into a minor issue. Boxstarter complains about a non existing function:
image

It seems that adding `Install-BoxstarterExtension` to `BoxStarter.Bootstrapper.psm1` solves this issue.

**Comment by Baune8D** [comment]
I am also still seeing alot of irrelevant verbose information in the terminal window when installing Chocolatey packages (As described in https://github.com/chocolatey/boxstarter/pull/479#issuecomment-956450311) :
image
image
But i am not experiencing any loops anymore and installation seems to progress correctly.

**Comment by mwallner** [comment]
> @mwallner Excited to give this another run! smile
> 
> I'm currently running into a minor issue. Boxstarter complains about not being able to find `Install-BoxstarterExtension`:
> 
> image
> 
> It seems that adding `Install-BoxstarterExtension` to `BoxStarter.Bootstrapper.psm1` solves this issue.

Good Catch!
I actually forgot to commit the change after I moved from `Setup-` to `Install-` in order to use approved verbs.
(explains why I haven't seen this in my demo env also x_x)

**Comment by flcdrg** [comment]
Doing some testing with the latest build off of Appveyor. Ran it using [this Boxstarter script](https://gist.githubusercontent.com/flcdrg/87802af4c92527eb8a30/raw/5cf0fc46a72f0142261d921427ca36e2cd8a04b5/boxstarter-bare-v3.ps1).

Did notice this seems to have failed with an odd error:

image

and from boxstarter.log

```text
[2021-11-24T10:48:55.9572338+00:00:::PID 4688] Boxstarter: calling actual choco.exe now with 'Install dotUltimate --params '/NoCpp /NoTeamCityAddin /NoRider' -Source C:\ProgramData\Boxstarter\BuildPackages;https://chocolatey.org/api/v2 -Verbose -y'
[2021-11-24T10:48:55.9602304+00:00:::PID 4688] Boxstarter: setting current directory location to C:\Windows\system32
[2021-11-24T10:48:55.9622306+00:00:::PID 4688] Boxstarter: BoxstarterWrapper::Run(Install dotUltimate --params '/NoCpp /NoTeamCityAddin /NoRider' -Source C:\ProgramData\Boxstarter\BuildPackages;https://chocolatey.org/api/v2 -Verbose -y)...
[2021-11-24T10:49:20.1258121+00:00:::PID 4688] Boxstarter: BoxstarterWrapper::Run => -1
[2021-11-24T10:49:20.1278109+00:00:::PID 4688] Boxstarter: restoring current directory location to C:\Windows\system32
[2021-11-24T10:49:20.1318111+00:00:::PID 4688] Boxstarter: Exit Code: -1
[2021-11-24T10:49:20.1446460+00:00:::PID 4688] Boxstarter: There was an error calling Chocolatey
```

It's now apparently got stuck waiting for beyondcompare to install:

```text
[2021-11-24T10:49:29.7463844+00:00:::PID 4688] Boxstarter: Current runtime is 4.0.30319.42000
[2021-11-24T10:49:29.7583845+00:00:::PID 4688] Boxstarter: calling actual choco.exe now with 'Install beyondcompare -Source C:\ProgramData\Boxstarter\BuildPackages;https://chocolatey.org/api/v2 -Verbose -y'
[2021-11-24T10:49:29.7603841+00:00:::PID 4688] Boxstarter: setting current directory location to C:\Windows\system32
[2021-11-24T10:49:29.7633847+00:00:::PID 4688] Boxstarter: BoxstarterWrapper::Run(Install beyondcompare -Source C:\ProgramData\Boxstarter\BuildPackages;https://chocolatey.org/api/v2 -Verbose -y)...
```

Not sure what happened there. I don't see the installer in memory anymore.

**Comment by flcdrg** [comment]
Tried this again, just running [this gist](https://gist.githubusercontent.com/flcdrg/87802af4c92527eb8a30/raw/f2863ceb71f794bad05b2c1b3aeace206eefc888/dotultimate.ps1)

I actually think I've seen the weird parsing of params in the current version of Boxstarter, but I don't think it causes errors (even though it looks wrong)

```text
Boxstarter: *** HELLO WORLD ***
+ Boxstarter starting Calling Chocolatey to install dotUltimate. This may take several minutes to complete...
Chocolatey v0.11.3
Installing the following packages:
dotUltimate;/NoTeamCityAddin;/NoRider'
By installing, you accept licenses for the packages.
[NuGet] Attempting to resolve dependency 'resharper-platform (= 212.0.20211001.131124)'.
Progress: Downloading resharper-platform 212.0.20211001.131124... 100%
Progress: Downloading dotUltimate 2021.2.2... 100%
[NuGet] Attempting to resolve dependency 'chocolatey-core.extension (≥ 1.3.1)'.
Progress: Downloading chocolatey-core.extension 1.3.5.1... 100%
[NuGet] Attempting to resolve dependency 'dotnet4.6.1 (≥ 4.6.01055.20170308)'.
Progress: Downloading DotNet4.6.1 4.6.01055.20170308... 100%
[NuGet] Attempting to resolve dependency 'KB2919355 (≥ 1.0.20160915)'.
Progress: Downloading KB2919355 1.0.20160915... 100%
[NuGet] Attempting to resolve dependency 'KB2919442 (≥ 1.0.20160915)'.
Progress: Downloading KB2919442 1.0.20160915... 100%
[NuGet] Installing 'resharper-platform 212.0.20211001.131124'.
[NuGet] Successfully installed 'resharper-platform 212.0.20211001.131124'.

resharper-platform v212.0.20211001.131124
resharper-platform package files install completed. Performing other installation steps.
ERROR: The string is missing the terminator: '.
The install of resharper-platform was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\resharper-platform\tools\chocolateyinstall.ps1'.
 See log for details.
```

**Comment by mwallner** [comment]
the essence of this PR should be summed up in [this blogpost](https://mwallner.net/posts/2021-11-28-boxstarter-v3/)

**Comment by Baune8D** [comment]
> the essence of this PR should be summed up in [this blogpost](https://mwallner.net/posts/2021-11-28-boxstarter-v3/)

@mwallner Great read! Really excited for the future of Boxstarter 😄 

However i am still expericing this problem i described earlier with verbose messages filling the output window when installing Boxstarter packages, i just tested again with 2.13.30-beta, and the issue persists.
https://github.com/chocolatey/boxstarter/pull/479#issuecomment-956450311
https://github.com/chocolatey/boxstarter/pull/479#issuecomment-975400315
If there is anything i can do to help debug this, please let me know.

Also i am still having a problem with remote installs, this time however it does not seem to relate to this PR, but to Windows 11 in generel. Whenever Boxstarter tries to restart the machine, it will reconnect the Powershell sessions before the restart actually happens, which ultimately leads to a failure to continue.
image

Boxstarter correctly detects the severed remote session as the restart is triggered, but will reconnect (see the red arrow in the image) before the machine actually restart, which leads to the I/O error in the image.

Again this is not related to the current PR (same problem in 2.13.0), so i should properly create a new issue for this, but right now it is preventing me from testing the versions remotely.

**Comment by mwallner** [comment]
Thanks for your feedback @Baune8D !
I actually thought I fixed the increased verbosity bug some commits ago but will re-check/fix that asap (in this PR)

As for the Win11 remoting issues you're facing: please create a separate issue for this - I'll have a look at it as soon as I'm done with this PR, I really want to focus on this first and keep the scope as focused/small as possible.

Thanks,

**Comment by flcdrg** [comment]
Not withstanding @Baune8D's comments, I do think the logging in this PR is a vast improvement on the current version (which pretty much doubles every line being logged) - so we're definitely heading in the right direction!

**Review by flcdrg — APPROVED** [review]

**Comment by mwallner** [comment]
rebased onto current master

**Comment by gep13** [comment]
@mwallner thanks for all your work in pulling this together, it is VERY much appreciated!

**Pull request merged**
