### PR TITLE
Invoke-BoxstarterFromTask

### PR DESCRIPTION
**Pull request by smaglio81**
Hey Mr. Wrock,

Here's the new function from the [RunAsTask thread](https://groups.google.com/forum/#!topic/boxstarter/f2Ro4HpVSQg).

Thanks for making this soo easy!

### CODE REVIEW

**Comment by mwrock** [comment]
Looks good and thanks so much for doing this. Just a few minor things I'd like to see:
1. Move the `Invoke-BoxstarterFromTask` function to its own file.
2. Optionally (I can do this if you rather) have `Invoke-ChocolateyFromTask` call this new function which should remove several lines from it.
3. Squash your commits

Thanks again!

**Comment by smaglio81** [comment]
1. I totally wanted to do that, so I'm more than happy to!
2. Can do!
3. I'll see what I can do. I'm new to git.

On Fri, Apr 29, 2016 at 10:40 AM, Matt Wrock <notifications@github.com>
wrote:

> Looks good and thanks so much for doing this. Just a few minor things I'd
> like to see:
> 1. Move the Invoke-BoxstarterFromTask function to its own file.
> 2. Optionally (I can do this if you rather) have Invoke-ChocolateyFromTask
> call this new function which should remove several lines from it.
> 3. Squash your commits
>
> Thanks again!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwrock/boxstarter/pull/176#issuecomment-215826023>
>



-- 
Steven Maglio
smaglio81@gmail.com
twitter: http://twitter.com/smaglio81
linkedin: http://www.linkedin.com/in/stevenmaglio
tech-blog: http://stevenmaglio.blogspot.com/

**Comment by mwrock** [comment]
I totally hear you on the git squash. Anything that changes history can be unsettling. However this is pretty easy (which is easy for me to say as I have to do it almost everyday as this is how my team works). Here are the steps I use to squash:
1. run `gitk` which will bring up an ugly (but effective) git history viewer
2. look for the first commit that is not yours. I'm assuming you see several of your commits sitting on top of my last commit
3. copy that commit hash
4. run `git reset <that git hash>`
5. if you now do a `git status` you should see all the files you touched as modified or untracked
6. now `git add` them all
7. do a `git commit -m 'message for all changes'`
8. `git push -f` to your branch. the `-f` is the key
9. BAM! squashed

**Comment by smaglio81** [comment]
Haha! Oh, I wish I had been checking email. Sorry.

I needed to get something finished up at work (Friday afternoon), so I went
a horrible way and deleted my repository/fork. Created a new fork from
yours, and the only commit in the future pull request will be this change.

I apologize for this, but I'm gonna send in a new pull request in a just a
minute.


On Fri, Apr 29, 2016 at 5:04 PM, Matt Wrock <notifications@github.com>
wrote:

> I totally hear you on the git squash. Anything that changes history can be
> unsettling. However this is pretty easy (which is easy for me to say as I
> have to do it almost everyday as this is how my team works). Here are the
> steps I use to squash:
> 1. run gitk which will bring up an ugly (but effective) git history viewer
> 2. look for the first commit that is not yours. I'm assuming you see
> several of your commits sitting on top of my last commit
> 3. copy that commit hash
> 4. run git reset <that git hash>
> 5. if you now do a git status you should see all the files you touched as
> modified or untracked
> 6. now git add them all
> 7. do a git commit -m 'message for all changes'
> 8. git push -f to your branch. the -f is the key
> 9. BAM! squashed
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mwrock/boxstarter/pull/176#issuecomment-215911488>
>



-- 
Steven Maglio
smaglio81@gmail.com
twitter: http://twitter.com/smaglio81
linkedin: http://www.linkedin.com/in/stevenmaglio
tech-blog: http://stevenmaglio.blogspot.com/

**Comment by mwrock** [comment]
no worries at all

**Pull request closed without merging**
