### PR TITLE
Chocolatey now uses httpS

### PR DESCRIPTION
**Pull request by aaranmcguire**
I get error 400 bad request when visiting via http, it looks they've made the site https now.

### CODE REVIEW

**Comment by gep13** [comment]
@aaranmcguire out of curiousity, was this causing you an error? The straight up http link still seems to work, although, perhaps it shouldn't.

Thoughts @ferventcoder?

**Comment by aaranmcguire** [comment]
Yh, I had to point the script I was using to my branch to get it to work.



—

**Comment by ferventcoder** [comment]
Like more than a year ago it converted to https.

**Comment by ferventcoder** [comment]
I think likely it was more like 2 years ago.

**Comment by gep13** [comment]
Is there a forced redirect in place between the http and https urls?

**Comment by mwrock** [comment]
http works for me but this is still the right thing to do.

**Comment by mwrock** [comment]
Thanks @aaranmcguire

**Comment by gep13** [comment]
>http works for me but this is still the right thing to do.

Oh, absolutely, I wasn't debating on that front :smile_cat:

**Comment by mwrock** [comment]
oh I know :)

**Pull request merged**
