### PR TITLE
Compatibility with latest Chocolatey

### PR DESCRIPTION
**Pull request by mwrock**
This is a work in progress adding support for using the chocolatey.dll instead of vendoring an internal and now very outdated chocolatey.

Note that at this point all unit tests are passing but I need to add a bunch more to catch up with changed behavior and then do some serious refactoring because much of the code is a cluster frickle frack but I think it is "working."

### CODE REVIEW

**Comment by lholman** [comment]
@mwrock Do you need any testing done on this branch, additional Unit Test coverage anywhere or any issues generated to keep track?

**Comment by mwrock** [comment]
@lholman if you want to do some additional testing that would be super. Right now it all works "on my box" via `Install-BoxstarterPackage` on local boxstarter runs and remote runs on guests running 8/2012 and up. Its broken on remote win 7/2008R2.

So more testing on those working platforms and issues about breakages would really be helpful. After getting remote win7/2008R2 working, I'm gonna start doing a combination of adding unit tests and refactoring. Currently alot of the code is a huge pile of poo that I twisted around just to make things work and I can barely comprehend myself how it works. So it needs alot of refactoring and cleanup.

**Comment by mwrock** [comment]
Remote 2k8r2 installs now working.

**Comment by mwrock** [comment]
All unit and integration tests are passing.

**Comment by lholman** [comment]
@mwrock Splendid, I'll get set-up and get all the tests running locally. Do you do anything automated/CI wise to check compatibility across OS versions, be good to understand your workflow.

**Comment by mwrock** [comment]
I have a unit test and integration test suite that I run.
```
./build.bat test # unit tests
./build.bat integration-test # integration tests
```
Note that the following are installed if not already present:
* psake
* 7zip
* pester
* nuget commandline
* azure powershell and .net lib

Most of the integration tests run on a VM and assume:
* a Hyper-V vm named win2k8r2 and win2012r2
* credentials: administrator/Pass@word1
See https://github.com/mwrock/boxstarter/blob/choco/IntegrationTests/EndToEnd.tests.ps1

These install packages `test-package` and `force-reboot` included in this repo and psake should build them before running the tests.

That all said, I can easily run those myself but what would be most helpful is to know that the real packages that folks use day to day still work on the platforms they normally use.

Thanks!

**Comment by lholman** [comment]
@mwrock Having a little trouble with the post build event of the BoxStarter.WebLaunch solution

```
EXEC : SignTool error : No certificates were found that met all the given criteria. [C:\Development\github\boxstarter\B
oxstarter.ClickOnce\Boxstarter.WebLaunch.csproj]
C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(4429,5): error MSB3073: The command ""C
:\Program Files (x86)\Windows Kits\8.1\bin\x64\signtool.exe" sign /n "Open Source Developer, Matthew Wrock" "C:\Develop
ment\github\boxstarter\Boxstarter.ClickOnce\obj\debug\Boxstarter.WebLaunch.exe"" exited with code 1. [C:\Development\gi
thub\boxstarter\Boxstarter.ClickOnce\Boxstarter.WebLaunch.csproj]
Error: 18/11/2015 07:55:35:
At C:\ProgramData\chocolatey\lib\psake.4.4.1\tools\psake.psm1:147 char:17 +                 throw ("Exec: " + $errorMes
sage) +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Exec: Error executing command  .$msbuildEx
e "$baseDir\Boxstarter.ClickOnce\Boxstarter.WebLaunch.csproj" /t:Build /v:minimal .
```

What do you usually do here, do you have a development cert, I couldn't see anything in the repo.

**Comment by mwrock** [comment]
I don't. However, I would just skip this since the web launcher has not yet been retrofitted. You could just comment out that task for now.

**Comment by mwrock** [comment]
Finished adding tests and refactorings - not perfect but better. All unit and integration tests are green (on my box).

Here is what this needs before moving forward:

1. Add a package that installs an MSI or EXE to the integration tests to add coverage for a critical path monkey patching chocolatey.
2. Ensure the click-once weblauncher is working. Pretty sure code needs to be added for win7/2k8r2 to run in .net4 runtime.
3. Pull in latest chocolatey.dll nuget package and make sure everything is still passing
4. Retrofit windows service reboot checks (Hopefully this works in latest chocolatey)

**Comment by mwrock** [comment]
Looks like The WindowsFeature code in the latest choco beta is broken. It puts `/all` in the wrong order of arguments given to `dism` when it needs to be last. Will be issuing a PR to fix.

**Comment by mwrock** [comment]
WindowsFeatures is the only outstanding issue to merging this and releasing. Once that is done, just need to do some sanity tests with some more "real world" boxstarter packages.

**Comment by ferventcoder** [comment]
Wow, you have been busy....

**Comment by mwrock** [comment]
ok. all integration and unit tests are passing with new chocolatey.dll dropped today incluing `WindowsFeature` packages. Building a win 10 vm and will be doing some more real life package tests that would match a real machine I would use. Once that is smooth this should be good to release.

**Comment by ferventcoder** [comment]
awesome!

**Comment by mwrock** [comment]
Pretty much ready to release now. Just need to do usual formalities of squashing, release notes, versioning, etc.

**Comment by gep13** [comment]
@mwrock this is great news! :smile:

**Comment by mwrock** [comment]
because i had already merged master onto this branch a couple times. I merged this and then reset to `origin/master` to squash.

**Pull request closed without merging**
