### PR TITLE
Disable-BingSearch

### PR DESCRIPTION
**Pull request by dhilgarth**
Disables the Bing Internet Search when searching from the search field
in the Taskbar or Start Menu.

### CODE REVIEW

**Comment by gep13** [comment]
@dhilgarth damn, you have been busy!  Great work :smile_cat:

**Comment by dhilgarth** [comment]
Thanks! :-)

There is something that bothers me. It's always the same code I am using:

    $path = "something"

    if(!(Test-Path $path)) {
        New-Item $path
    }

    New-ItemProperty -LiteralPath $path -Name "somename" -Value 0 -PropertyType "DWord" -ErrorAction SilentlyContinue
    Set-ItemProperty -LiteralPath $path -Name "somename" -Value 0

Usually, I would create a function for this and use that function in all the new features I am adding.
But:
1. I wouldn't know where to put that function
2. Because I am creating one PR per feature, I would need to include that file in each PR

However, thinking about 2., I already have a commit (e35cd80) that's included in all PRs.

Any hints on 1.?

**Comment by gep13** [comment]
@dhilgarth yes, there is definitely some repetition there that could be abstracted.  Perhaps a new function added to the Boxstarter.Common module:

https://github.com/mwrock/boxstarter/tree/master/BoxStarter.Common

**Comment by mwrock** [comment]
Yeah I'd really like to add some abstraction around all these registry toggles.

**Pull request merged**
